### ISSUE TITLE
Enable native compilation in emacs-git

### ISSUE THREAD

**Issue by innerout** [archlinuxcn/repo#1578] opened 2020-04-15 23:08 UTC
### 问题类型 / Type of issues

* 其它 / other

### 受影响的软件包 / Affected packages
* emacs-git

----
Since 01/01/2020 there is support for jit-compilation in Emacs master-branch. 
To enable it you need define at configure time the following argument ``--with-nativecomp`` .
For further information you can look in this post http://akrl.sdf.org/gccemacs.html .

**Comment by innerout** [comment] 2020-05-06 07:52
It seems there is a package already in AUR [emacs-native-comp](https://aur.archlinux.org/packages/emacs-native-comp-git ). Instead of changing the emacs-git package, a separate package could be pushed in archlinuxcn.

**Comment by yan12125** [comment] 2020-06-21 16:27
As of writing, `--with-nativecomp` option is still available only in the feature/native-comp branch but not the master branch, so that feature should be provided by a separate package. Closing as duplicate of #1584.

**Closed by yan12125** 2020-06-21 16:27 UTC
