### ISSUE TITLE
Binary package added by lilacbot

### ISSUE THREAD

**Issue by yuyichao** [archlinuxcn/repo#1484] opened 2020-02-08 17:35 UTC
### 问题类型 / Type of issues

* 打包错误 / packaging error

### 受影响的软件包 / Affected packages

* pip-tools

----

请在此补充说明。
Please describe in detail here.

A binary package is added in https://github.com/archlinuxcn/repo/commit/f518c325baf7a08b439c8a29fe81507a7713e03f by lilac, even though the file is configured to be ignored by git (`*.tar.*`)...

Was is intended? (if so, why?) Was this due to a bug in lilac?

**Comment by lilydjwg** [comment] 2020-02-09 04:18
It's intended by the AUR maintainer: https://aur.archlinux.org/cgit/aur.git/tree/?h=pip-tools
This is not a bug in lilac. lilac is accurately added all files the AUR maintainer has added, no more, no less.

**Comment by yan12125** [comment] 2020-03-06 03:00
The AUR maintainer removed that file in [2], but the corresponding update [2] in this repo does not fully reflect that change.

[1] https://aur.archlinux.org/cgit/aur.git/commit/?h=pip-tools&id=ac190fa57871a262c0ee0b672193e97d3504aea5
[2] 99d9cf6439d91232aae7960c74ee4052d059c58e

**Comment by lilydjwg** [comment] 2020-03-07 14:07
This should be fixed on next lilac update.

**Comment by yan12125** [comment] 2020-03-07 14:50
Thanks for the efforts!

**Closed** 2020-04-01 09:21 UTC
