### ISSUE TITLE
firefox-kde-opensuse is out-of-date

### ISSUE THREAD

**Issue by zoe12345** [archlinuxcn/repo#760] opened 2018-06-02 07:20 UTC
### 问题类型 / Type of issues
60.0.1 is available
* 过期软件包 / out-of-date packages
firefox-kde-opensuse (59.0.2)
### 受影响的软件包 / Affected packages

* （请在此填写包名，每行一个，开头加上星号 / package names, one per line）

----

**Comment by yan12125** [comment] 2018-06-02 07:41
Duplicate of #724

**Closed by yan12125** 2018-06-02 07:41 UTC
Labels: out-of-date
